name: deploy event triggered lambda
on:
  push: # Runs on every push to main branch
    branches:
      - release/prod_byevent
      - release/staging_byevent
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Determine lambda to deploy
        run: |
          case "${{ github.ref }}" in
            refs/heads/release/staging_byevent)
              FUNCTION_NAME="stg-${{secrets.FUNCTION_NAME}}"
              AWS_ACCESS_KEY_ID="${{ secrets.STG_AWS_ACCESS_KEY_ID }}"
              AWS_SECRET_ACCESS_KEY="${{ secrets.STG_AWS_SECRET_ACCESS_KEY }}"
              AWS_IAM_ROLE="${{ secrets.STG_AWS_IAM_ROLE }}"
              ;;
            refs/heads/release/prod_byevent)
              FUNCTION_NAME="prod-${{secrets.FUNCTION_NAME}}"
              AWS_ACCESS_KEY_ID="${{ secrets.PROD_AWS_ACCESS_KEY_ID }}"
              AWS_SECRET_ACCESS_KEY="${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}"
              AWS_IAM_ROLE="${{secrets.PROD_AWS_IAM_ROLE}}"
              ;;
            esac
            
            # FUNCTION_NAME
            echo "FUNCTION_NAME=$FUNCTION_NAME" >> $GITHUB_ENV
            # AWS_ variables contain credentials for authenticating with AWS prior to deploying.
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
            echo "AWS_IAM_ROLE=$AWS_IAM_ROLE" >> $GITHUB_ENV

      - name: zip function by event trigger
        run: |
          cd lambda && zip doc-shredding.zip s3mv.py triggered_by_event.py
         
      - name: Login to the AWS environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          role-duration-seconds: 1200
          role-session-name: GHA-${{ github.sha }}
          aws-region: eu-west-1
      
      - name: Update function
        run: |
          aws lambda update-function-code \
            --function-name  ${{ env.FUNCTION_NAME }} \
            --zip-file fileb://lambda/doc-shredding.zip